(function(){
var e=navigator.userAgent.toLowerCase();google.isOpera=e.indexOf("opera")!=-1;google.isIE=document.all&&e.indexOf("msie")!=-1&&!google.isOpera;google.isSafari=e.indexOf("safari")!=-1;google.time=function(){return(new Date).getTime()};google.log=function(a,d){(new Image).src="/gen_204?atyp=i&ct="+a+"&cad="+d+"&zx="+google.time()};google.xhr=function(){var a=null;if(window.XMLHttpRequest)try{a=new XMLHttpRequest}catch(d){}else if(window.ActiveXObject)for(var b=0,c;c=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0",
"MSXML2.XMLHTTP","Microsoft.XMLHTTP"][b++];)try{a=new ActiveXObject(c);break}catch(d){}return a};function h(a,d){var b=document.defaultView&&document.defaultView.getComputedStyle(a,""),c=b&&b.getPropertyValue(d);return document.defaultView&&b&&typeof c=="string"&&parseInt(c,10)}google.getHeight=function(a){return h(a,"height")||a.offsetHeight};google.getWidth=function(a){return h(a,"width")||a.offsetWidth};google.rhs=function(){};window.google.bind=function(a,d,b){var c="on"+d;if(a.addEventListener)a.addEventListener(d,b,false);else if(a.attachEvent)a.attachEvent(c,b);else{var i=a[c];a[c]=function(){var f=i.apply(this,arguments),g=b.apply(this,arguments);return f==undefined?g:(g==undefined?f:g&&f)}}};
})();
(function(){
window.google.stringify=function(a){var c,d,i,b="",e;switch(typeof a){case "object":if(a)if(a instanceof Array||typeof a.join=="function"&&typeof a.reverse=="function"){for(d=0;d<a.length;++d){e=window.google.stringify(a[d]);if(b)b+=",";b+=e}return"["+b+"]"}else if(typeof a.toString!="undefined"){for(d in a){e=a[d];if(typeof e!="undefined"&&typeof e!="function"){e=window.google.stringify(e);if(b)b+=",";b+=window.google.stringify(d)+":"+e}}return"{"+b+"}"}return"null";case "number":return isFinite(a)?
String(a):"null";case "string":i=a.length;b='"';for(d=0;d<i;d+=1){c=a.charAt(d);if(c>=" "){if(c=="\\"||c=='"')b+="\\";b+=c}else switch(c){case "\n":b+="\\n";break;case "\r":b+="\\r";break;case "\t":b+="\\t";break;default:c=c.charCodeAt();b+="\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16);break}}return b+'"';case "boolean":return String(a);default:return"null"}};google.History={};var f=[];google.History.client=function(a){f.push(a);return f.length-1};var g=document.getElementById("hcache"),h=null;function j(){var a=g.value;h=!(!a)?eval("("+a+")"):{}}google.History.save=function(a,c){if(g){j();h[a]=c;g.value=google.stringify(h)}};g&&window.setTimeout(function(){j();for(var a=0;a<f.length;++a)if(h&&h[a])f[a].call(null,h[a])},0);
})();
(function(){
var a=document.getElementById("tads"),b=document.getElementById("3po");google.rhs=function(){if(!google.drhs)if(document.getElementById("mbEnd")&&(a||b)){var d=google.getHeight(document.getElementById("rhsline")),c=a?google.getHeight(a):0;if(b)c+=google.getHeight(b)+18;document.getElementById("rhspad").style.height=c>d?Math.min(9999,c-d)+"px":(google.isIE?"":0)}};google.rhs();google.bind(window,"resize",google.rhs);
})();
(function(){
window.ManyBox={};var e={},g={},h=1,j=google.History.client(i),k;function l(a){for(var b in e)if(e[b].c&&a(e[b]))return}function m(a,b,c,d,f){this.c=a;this.i=b;this.B=d;this.o=f;this.q="/mbd?"+(b?"docid="+b:"")+"&resnum="+a.replace(/[^0-9]/,"")+"&mbtype="+d+"&usg="+c+"&hl="+(google.kHL||"");this.e={};this.l="";g[a]={r:0,D:this.e,i:this.i,h:0};this.n=0}m.prototype.append=function(a){this.l="&"+a.join("&")};function n(a,b){return document.getElementById("mb"+b+a.c)}function o(a,b){a.g.style.paddingTop=
b+"px";a.g.style.display=a.g.innerHTML?"":"none";if(b>a.n)a.n=b}function r(a){if(!a.A){a.A=1;a.d=n(a,"b");a.j=0;a.a=n(a,"l");a.m=a.a.getElementsByTagName("DIV")[0];a.p=a.a.getElementsByTagName("A")[0];a.z=a.p.innerHTML;a.o=a.o||a.z;a.m.title="Klik voor meer informatie";a.a.F=function(b,c){var d=s(a.a),f=t(a.a);return b>d-5&&b<d+google.getWidth(a.a)+5&&c>f-5&&c<f+google.getHeight(a.a)+5};a.g=n(a,"f");o(a,0);a.a.onmousedown=u(a);a.a.onclick=v(a);a.a.go=function(){a.a.onmousedown();a.a.onclick()}}}function u(a){return function(){if(g[a.c].h){if(a.I++<3)google.log("manybox",[a.j?"close":"open","&id=",a.c,"&docid=",a.i,"&mbtype=",a.B,a.l].join(""))}else{var b=google.xhr();if(b){b.open("GET",a.q+a.l+"&zx="+google.time());a.t=0;b.onreadystatechange=function(){if(b.readyState==4){var c=0;if(b.status==200)try{eval(b.responseText);c=1}catch(d){}if(!c&&!a.C){g[a.c].h=0;a.C=1;a.q+="&cad=retry";a.a.onmousedown()}else{a.u&&z(a);a.t=0}}};a.t=1;b.send(null)}g[a.c].h=(a.I=1)}}}function v(a){return function(){g[a.c].h||
a.a.onmousedown();(a.u=a.t)||z(a)}}function A(a){if(!a.e.k){a.e.k="\x3cfont color\x3dred\x3eFout:\x3c/font\x3e de server kan uw verzoek niet voltooien. Probeer het over 30 seconden nogmaals.";a.G=a.a.onclick;a.a.onclick=function(){h=0;z(a);h=1;a.b.parentNode.removeChild(a.b);g[a.c].h=(a.e.k=(a.v=0));a.a.onclick=a.G}}if(!a.v){a.v=1;a.H=document.getElementById("mbEnd")&&s(a.d)>s(document.getElementById("mbEnd"));a.b=document.createElement("div");o(a,0);a.b.style.position="absolute";a.b.style.paddingTop=(a.b.style.paddingBottom="6px");a.b.style.display="none";a.b.className="med";var b=document.createElement("div");
a.b.appendChild(b);b.className="std";b.innerHTML=a.e.k;a.g.parentNode.insertBefore(a.b,a.g)}}function i(a){h=0;ManyBox.init();l(function(b){if(b.i==a[b.c].i){b.e=a[b.c].D;if(a[b.c].r!=b.j)z(b)}else a[b.c].h=0});g=a;h=1;google.History.save(j,g)}ManyBox.create=function(a,b,c,d,f){return new m(a,b,c,d,f)};ManyBox.register=function(a,b,c,d,f){return e[a]=ManyBox.create(a,b,c,d,f)};ManyBox.init=function(){if(!k){history.navigationMode=
history.navigationMode&&"fast";l(r);google.bind(document,"click",function(a){a=a||window.event;var b=a.target||a.srcElement;while(b.parentNode){if(b.tagName=="A"||b.onclick)return;b=b.parentNode}l(function(c){if(c.a.F(a.clientX,a.clientY)){c.a.go();return 1}})});k=1}};function B(a,b){a.b.style.clip="rect(0px,"+(a.d.width||"34em")+","+(b||1)+"px,0px)"}m.prototype.insert=function(a){this.e.k=a;google.History.save(j,g)};function t(a){return a.offsetTop+(a.offsetParent?t(a.offsetParent):0)}function C(a){return a.offsetLeft+
(a.offsetParent?C(a.offsetParent):0)}function s(a){return C(a)}function D(a){a.f=n(a,"cb");var b=a.f&&a.f.getAttribute("mbopen");if(b){eval(b);a.onopen(a.f)}}function E(a){a.b.style.display="none";a.m.style.backgroundPosition="-114px -78px";a.p.innerHTML=a.z;a.j=(g[a.c].r=0);google.History.save(j,g)}function F(a,b,c,d,f){var w=c>0?150:75,x=google.time()-f,y=x<w&&h?x/w*c:(d>1?c-10:c),p=Math.max(a.s,b+y),q=p-a.s;B(a,q);a.d.style.height=
p<0?0:(q?p+"px":"");o(a,Math.max(0,q-5));google.rhs();if(Math.abs(y)<Math.abs(c))window.setTimeout(function(){F(a,b,c,d-1,f)},30);else window.setTimeout(function(){c<0?E(a):D(a);if(!google.isIE&&a.H)a.b.style.width="100px";a.b.style.position=(a.d.style.height="");o(a,0);google.rhs();a.d.w=0},0)}function z(a){a.u=0;if(!a.d.w){a.d.w=1;var b;if(!a.j){a.s=google.getHeight(a.d);A(a);o(a,0);a.n=0;l(function(d){d.m.title=""});a.m.style.backgroundPosition="-126px -78px";a.p.innerHTML=a.o;B(a,1);a.b.style.position=
"absolute";a.b.style.display="";a.j=(g[a.c].r=1);google.History.save(j,g);b=a.b.offsetHeight}else{var c=a.f&&a.f.getAttribute("mbclose");if(c){eval(c);a.onclose(a.f)}b=a.s-google.getHeight(a.d);a.g.style.display="none";o(a,a.n);a.b.style.position="absolute"};F(a,google.getHeight(a.d),b,google.isSafari?2:1,google.time())}};
})();
if(!window.gbar||!gbar.close){window.gbar={};(function(){var b=window.gbar,f,h;b.qs=function(a){var c=window.encodeURIComponent&&(document.forms[0].q||"").value;if(c)a.href=a.href.replace(/([?&])q=[^&]*|$/,function(i,g){return(g||"&")+"q="+encodeURIComponent(c)})};function j(a,c){a.visibility=h?"hidden":"visible";a.left=c+"px"}b.tg=function(a){a=a||window.event;var c=0,i,g=window.navExtra,d=document.getElementById("gbi"),e=a.target||a.srcElement;a.cancelBubble=true;if(!f){f=document.createElement(Array.every||window.createPopup?"iframe":"div");f.frameBorder="0";f.src="#";d.parentNode.appendChild(f).id="gbs";if(g)for(i in g)d.insertBefore(g[i],d.firstChild).className="gb2";document.onclick=b.close}if(e.className!="gb3")e=e.parentNode;do c+=e.offsetLeft;while(e=e.offsetParent);j(d.style,c);f.style.width=d.offsetWidth+"px";f.style.height=d.offsetHeight+"px";j(f.style,c);h=!h};b.close=function(a){h&&b.tg(a)}})();;};
(function (){
var a="google";if(window[a]){window[a].a={};window[a].b=1;window[a].report=function(h,g,i){var d="";{if(window[a].pt){d+="&srt="+window[a].pt;delete window[a].pt}try{d+="&tran="+window.external.tran}catch(n){}}{var j=document.getElementById("csi");if(j.value)return;j.value=1}var b=h.t,e=b.start;delete b.start;var k=[];for(var f in b)e&&k.push(f+"."+(b[f]>e?b[f]-e:e-b[f]));if(g)for(var l in g)d+="&"+l+"="+g[l];var c=new Image,m=window[a].b++;window[a].a[m]=c;c.onload=(c.onerror=function(){delete window[a].a[m]});
c.src=[i?i:"/csi","?v=3","&s="+(window[a].sn?window[a].sn:"GWS")+"&action=",h.name,d,"&rt=",k.join(",")].join("");c=null}};google.timers.load.t.xjs=(new Date).getTime();google.timers.load.t.ol&&google.report(google.timers.load,{ei:google.kEI,e:google.kEXPI});
})();
if(google.y.first){for(var a=0,b;b=google.y.first[a];++a)b();delete google.y.first}for(a in google.y)google.y[a][1]?google.y[a][1].apply(google.y[a][0]):google.y[a][0].go();google.x=function(d,c){c&&c.apply(d);return false};
