'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADO_project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property MySql_Data() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MySql_Data", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''
        '''CREATE TABLE tblNiveau
        '''(
        '''NiveauID INT NOT NULL
        '''IDENTITY(1,1) PRIMARY KEY,
        '''Niveau VARCHAR(50) NOT NULL
        ''');
        '''
        '''CREATE TABLE tblSport
        '''(
        '''SportID INT NOT NULL
        '''IDENTITY(1,1) PRIMARY KEY,
        '''SportNaam VARCHAR(50) NOT NULL
        ''');
        '''
        '''CREATE TABLE tblStudent
        '''(
        '''StudentID INT NOT NULL
        '''IDENTITY(1,1) PRIMARY KEY,
        '''StudentNaam VARCHAR(50) NOT NULL,
        '''StudentVoornaam VARCHAR(50) NOT NULL,
        '''StudentGSM VARCHAR(50) NOT NULL,
        '''StudentSchoolEmail VARCHAR(50) NOT NULL,
        '''StudentPriveEmail VARCHAR(50) NOT NULL,
        '''StudentGeb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property startdata() As String
            Get
                Return ResourceManager.GetString("startdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_datainlezen
        '''
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	SELECT * FROM tblDoetSport, tblNiveau, tblSport, tblStudent
        '''END
        '''.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_datainlezen() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_datainlezen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_nieuwedeelname
        '''	-- Add the parameters for the stored procedure here
        '''	@tempSportID INT, @tempStudentID  INT, @tempNiveauID INT
        '''AS
        '''BEGIN
        '''
        '''	SET NOCOUNT ON;
        '''
        '''	INSERT INTO tblDoetSport(SportID,LidID,NiveauID)
        '''	SELECT A.SportID, B.StudentID, C.NiveauID
        '''	FROM (SELECT SportID FROM tblSport WHERE SportID = @tempSportID) A,
        '''	(SELECT StudentID FROM tblStudent WHERE StudentID = @tempStudentID) B,
        '''	(SELECT NiveauID FROM tblNiveau WHERE NiveauID = @tempNiveauID) C
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_nieuwedeelname() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_nieuwedeelname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_nieuwesport
        '''	@tempSport VARCHAR(50), @tempSportID INT OUTPUT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	INSERT INTO tblSport(SportNaam) VALUES(@tempSport)
        '''	SELECT @@IDENTITY AS [@@IDENTITY]
        '''	SET @tempSportID = @@IDENTITY
        '''END
        '''.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_nieuwesport() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_nieuwesport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_nieuwestudent
        '''	@tempNaam VARCHAR(50), @tempVoornaam VARCHAR(50), @tempGSM VARCHAR(50),
        '''	@tempSchoolmail VARCHAR(50), @tempPrivemail VARCHAR(50), @tempGebDat DATETIME, 
        '''	@tempFinRek VARCHAR(20), @tempStudentID INT OUTPUT
        '''AS
        '''BEGIN
        '''	SET DATEFORMAT dmy
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	INSERT INTO tblStudent( StudentNaam , StudentVoornaam , StudentGSM ,
        '''	StudentSchoolEmail , StudentP [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_nieuwestudent() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_nieuwestudent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_nieuwniveau 
        '''	@tempNiveau VARCHAR(50), @tempNiveauID INT OUTPUT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''    -- Insert statements for procedure here
        '''	INSERT INTO tblNiveau(Niveau) VALUES(@tempNiveau)
        '''	SELECT @@IDENTITY AS [@@IDENTITY]
        '''	SET @tempNiveauID = @@IDENTITY
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_nieuwniveau() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_nieuwniveau", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_tbldoetsportdatagrid
        '''	
        '''AS
        '''BEGIN
        '''	
        '''	SET NOCOUNT ON;
        '''	SELECT StudentNaam, SportNaam, Niveau
        '''	FROM tblDoetSport inner join tblStudent ON (tblDoetSport.LidID = tblStudent.StudentID) 
        '''	inner join tblSport ON (tblDoetSport.SportID = tblSport.SportID) 
        '''	inner join tblNiveau ON (tblDoetSport.NiveauID = tblNiveau.NiveauID);
        '''  
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_tbldoetsportdatagrid() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_tbldoetsportdatagrid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_tbldoetsportinlezen
        '''AS
        '''BEGIN
        '''	SET NOCOUNT ON;
        '''
        '''    -- Insert statements for procedure here
        '''	SELECT * FROM tblDoetSport
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_tbldoetsportinlezen() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_tbldoetsportinlezen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_tblniveauinlezen
        '''AS
        '''BEGIN
        '''	SET NOCOUNT ON;
        '''
        '''    -- Insert statements for procedure here
        '''	SELECT * FROM tblNiveau
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_tblniveauinlezen() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_tblniveauinlezen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_tblsportinlezen
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	SELECT * FROM tblSport
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_tblsportinlezen() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_tblsportinlezen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_tblstudentinlezen
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	SELECT * FROM tblStudent
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_tblstudentinlezen() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_tblstudentinlezen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_updatesport
        '''	@tempSport VARCHAR(50), @tempSportID INT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	UPDATE tblSport SET SportNaam = @tempSport WHERE SportID = @tempSportID
        '''END
        '''.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_updatesport() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_updatesport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_updatestudent
        '''	@tempNaam VARCHAR(50), @tempVoornaam VARCHAR(50), @tempGSM VARCHAR(50),
        '''	@tempSchoolmail VARCHAR(50), @tempPrivemail VARCHAR(50), @tempGebDat DATETIME, 
        '''	@tempFinRek VARCHAR(20), @tempStudentID INT
        '''AS
        '''BEGIN
        '''	SET DATEFORMAT dmy
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	UPDATE tblStudent
        '''	SET StudentNaam = @tempNaam, StudentVoornaam = @tempVoornaam, StudentGSM = @tempGSM ,
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_updatestudent() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_updatestudent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_verwijdersport
        '''	@tempSportID INT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	DELETE FROM tblSport WHERE @tempSportID = SportID
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_verwijdersport() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_verwijdersport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE PROCEDURE STORED_PROCEDURE_verwijderstudent
        '''	@tempStudentID INT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	DELETE FROM tblStudent WHERE @tempStudentID = StudentID
        '''END.
        '''</summary>
        Friend ReadOnly Property STORED_PROCEDURE_verwijderstudent() As String
            Get
                Return ResourceManager.GetString("STORED_PROCEDURE_verwijderstudent", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
