

CREATE TABLE tblNiveau
(
NiveauID INT NOT NULL
IDENTITY(1,1) PRIMARY KEY,
Niveau VARCHAR(50) NOT NULL
);

CREATE TABLE tblSport
(
SportID INT NOT NULL
IDENTITY(1,1) PRIMARY KEY,
SportNaam VARCHAR(50) NOT NULL
);

CREATE TABLE tblStudent
(
StudentID INT NOT NULL
IDENTITY(1,1) PRIMARY KEY,
StudentNaam VARCHAR(50) NOT NULL,
StudentVoornaam VARCHAR(50) NOT NULL,
StudentGSM VARCHAR(50) NOT NULL,
StudentSchoolEmail VARCHAR(50) NOT NULL,
StudentPriveEmail VARCHAR(50) NOT NULL,
StudentGebDat DATETIME NOT NULL,
StudentFinRek VARCHAR(20) NOT NULL,
);

CREATE TABLE tblDoetSport
(
DoetSportID INT NOT NULL
IDENTITY(1,1) PRIMARY KEY,
SportID INT NOT NULL FOREIGN KEY REFERENCES tblSport (SportID),
LidID INT NOT NULL FOREIGN KEY REFERENCES tblStudent (StudentID),
NiveauID INT NOT NULL FOREIGN KEY REFERENCES tblNiveau (NiveauID)
);

INSERT INTO tblNiveau VALUES('< Nieuw Niveau >');