'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ADO_project.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO tblNiveau VALUES(&apos;&lt; Nieuw Niveau &gt;&apos;).
        '''</summary>
        Friend ReadOnly Property startdata() As String
            Get
                Return ResourceManager.GetString("startdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SET ANSI_NULLS ON
        '''GO
        '''SET QUOTED_IDENTIFIER ON
        '''GO
        '''CREATE PROCEDURE STORED_PROCEDURE_nieuwesport
        '''	@tempSport VARCHAR(50), @tempSportID INT OUTPUT
        '''AS
        '''BEGIN
        '''	-- SET NOCOUNT ON added to prevent extra result sets from
        '''	-- interfering with SELECT statements.
        '''	SET NOCOUNT ON;
        '''
        '''	INSERT INTO tblSport(SportNaam) VALUES(@tempSport)
        '''	SELECT @@IDENTITY AS [@@IDENTITY]
        '''	SET @tempSportID = @@IDENTITY
        '''END
        '''GO
        '''
        '''SET ANSI_NULLS ON
        '''GO
        '''SET QUOTED_IDENTIFIER ON
        '''GO
        '''CREATE PROCEDURE STORED_PROCEDURE_updatesport [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property stored_procedures() As String
            Get
                Return ResourceManager.GetString("stored_procedures", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
